preload = ~/Pictures/wallpaper/wallhaven-28kdom.png
preload = ~/Pictures/wallpaper/wallhaven-45ypo5.jpg
wallpaper = DP-1,~/Pictures/wallpaper/wallhaven-28kdom.png
wallpaper = DP-2,~/Pictures/wallpaper/wallhaven-45ypo5.jpg
