preload = ~/Pictures/wallpaper/wallhaven-qzkw1d.jpg
preload = ~/Pictures/wallpaper/wallhaven-45ypo5.jpg
wallpaper = DP-1,~/Pictures/wallpaper/wallhaven-qzkw1d.jpg
wallpaper = DP-2,~/Pictures/wallpaper/wallhaven-45ypo5.jpg
